version: '3.3'

services:
  mysql:
    container_name: rooms_db
    image: mysql
    ports:
    - 3308:3306
    restart: always
    #command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./rooms/database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: rooms
      MYSQL_ROOT_PASSWORD: 1YaKN6M6dP13
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: rooms_user
      MYSQL_PASSWORD: 1YaKN6M6dP13

  server:
    restart: always
    image: thkoeln/rooms_server
    container_name: rooms_server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/rooms?autoReconnect=true
      SPRING_DATASOURCE_USERNAME: rooms_user
      SPRING_DATASOURCE_PASSWORD: 1YaKN6M6dP13
    volumes:
      - ./rooms/server:/rooms
    ports:
    - 8085:8080
    depends_on:
    - mysql